# ─── MOCK BOOK DATA ───────────────────────────────────────────────────────────
# Fake book requests used until a real database table exists.
# Kept in its own file so views.py stays readable and this list can grow
# without touching routing logic.
#
# Each dict mirrors what a real DB row would look like, so swapping in a
# real query later only requires changing where MOCK_BOOKS comes from.

MOCK_BOOKS = [
    {
        "id": "1",
        "title": "Old Dalmatian Maritime Records",
        "author": "Unknown",
        "language": "hr",
        "country": "Croatia",
        "city": "Split",
        "library": "University Library Split",
        "request_count": 24,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "2",
        "title": "Stone Inscriptions of the Adriatic",
        "author": "Petar Novak",
        "language": "hr",
        "country": "Croatia",
        "city": "Split",
        "library": "University Library Split",
        "request_count": 11,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "3",
        "title": "Venetian Trade Routes 1400–1600",
        "author": "Marco Foscari",
        "language": "it",
        "country": "Croatia",
        "city": "Dubrovnik",
        "library": "Dubrovnik State Archive",
        "request_count": 38,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "4",
        "title": "Medieval Herbal Medicine",
        "author": "Anna Horvat",
        "language": "hr",
        "country": "Croatia",
        "city": "Zagreb",
        "library": "National and University Library Zagreb",
        "request_count": 17,
        "risk_level": "low",
        "is_digitized": True,  # already done — will score low
    },
    {
        "id": "5",
        "title": "Habsburg Administrative Decrees Vol. III",
        "author": "K. Schmid",
        "language": "de",
        "country": "Austria",
        "city": "Vienna",
        "library": "Austrian National Library",
        "request_count": 45,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "6",
        "title": "Alpine Folklore and Songs",
        "author": "E. Brauer",
        "language": "de",
        "country": "Austria",
        "city": "Innsbruck",
        "library": "University of Innsbruck Library",
        "request_count": 8,
        "risk_level": "low",
        "is_digitized": False,
    },
    {
        "id": "7",
        "title": "Ottoman Land Registry — Bosnia 1870",
        "author": "Unknown",
        "language": "tr",
        "country": "Bosnia and Herzegovina",
        "city": "Sarajevo",
        "library": "Archives of Bosnia-Herzegovina",
        "request_count": 62,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "8",
        "title": "Sarajevo Street Directories 1920–1940",
        "author": "Various",
        "language": "sr",
        "country": "Bosnia and Herzegovina",
        "city": "Sarajevo",
        "library": "Archives of Bosnia-Herzegovina",
        "request_count": 19,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "9",
        "title": "Prewar Budapest Telephone Books",
        "author": "Budapest City Council",
        "language": "hu",
        "country": "Hungary",
        "city": "Budapest",
        "library": "National Széchényi Library",
        "request_count": 80,
        "risk_level": "low",
        "is_digitized": True,
    },
    {
        "id": "10",
        "title": "Transylvanian Church Records",
        "author": "Unknown",
        "language": "ro",
        "country": "Romania",
        "city": "Cluj-Napoca",
        "library": "Cluj County Library",
        "request_count": 33,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "11",
        "title": "Polish Resistance Underground Press 1943",
        "author": "Various",
        "language": "pl",
        "country": "Poland",
        "city": "Warsaw",
        "library": "Warsaw University Library",
        "request_count": 55,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "12",
        "title": "Gdańsk Merchant Guild Ledgers",
        "author": "Guild of St. George",
        "language": "de",
        "country": "Poland",
        "city": "Gdańsk",
        "library": "Gdańsk Library of the Polish Academy",
        "request_count": 27,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "13",
        "title": "Prague Spring Pamphlets",
        "author": "Various",
        "language": "cs",
        "country": "Czech Republic",
        "city": "Prague",
        "library": "National Library of the Czech Republic",
        "request_count": 41,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "14",
        "title": "Serbian Orthodox Monastery Codex",
        "author": "Unknown",
        "language": "sr",
        "country": "Serbia",
        "city": "Novi Sad",
        "library": "Matica srpska Library",
        "request_count": 29,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "15",
        "title": "Istrian Land Survey Maps 1780",
        "author": "Imperial Survey Office",
        "language": "it",
        "country": "Croatia",
        "city": "Pula",
        "library": "State Archive Pazin",
        "request_count": 16,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "16",
        "title": "Dalmatian Cookbook Manuscripts",
        "author": "Unknown",
        "language": "hr",
        "country": "Croatia",
        "city": "Split",
        "library": "Museum of Croatian Archaeological Monuments",
        "request_count": 7,
        "risk_level": "low",
        "is_digitized": False,
    },
    {
        "id": "17",
        "title": "Bulgarian National Revival Journals",
        "author": "Various",
        "language": "bg",
        "country": "Bulgaria",
        "city": "Sofia",
        "library": "SS Cyril and Methodius National Library",
        "request_count": 34,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "18",
        "title": "Greek Shipping Manifests — Piraeus 1905",
        "author": "Port Authority of Piraeus",
        "language": "el",
        "country": "Greece",
        "city": "Athens",
        "library": "National Library of Greece",
        "request_count": 48,
        "risk_level": "high",
        "is_digitized": False,
    },
    {
        "id": "19",
        "title": "Krakow University Lecture Transcripts 1890",
        "author": "Various",
        "language": "pl",
        "country": "Poland",
        "city": "Kraków",
        "library": "Jagiellonian Library",
        "request_count": 22,
        "risk_level": "medium",
        "is_digitized": False,
    },
    {
        "id": "20",
        "title": "Bohemian Mining Regulations 1550",
        "author": "Joachim Gärtner",
        "language": "de",
        "country": "Czech Republic",
        "city": "Prague",
        "library": "National Library of the Czech Republic",
        "request_count": 12,
        "risk_level": "low",
        "is_digitized": True,
    },
]
