import type { BookRequest } from './types';

// ─── SEED DATA ────────────────────────────────────────────────────────────────
// 20 hand-written mock books. Deliberately spread across multiple countries,
// cities, and languages so filters and scoring produce varied, testable results.
//
// Design choices:
//   - Several books share the same city/library so library-match scoring is visible
//   - Some books are already digitized to test "hide digitized" filter
//   - Request counts range widely (1–80) so demand score creates spread
//   - All three risk levels are represented
export const SEED_BOOKS: BookRequest[] = [
  {
    id: '1',
    title: 'Old Dalmatian Maritime Records',
    author: 'Unknown',
    language: 'Croatian',
    country: 'Croatia',
    city: 'Split',
    library: 'University Library Split',
    requestCount: 24,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '2',
    title: 'Stone Inscriptions of the Adriatic',
    author: 'Petar Novak',
    language: 'Croatian',
    country: 'Croatia',
    city: 'Split',
    library: 'University Library Split',
    requestCount: 11,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '3',
    title: 'Venetian Trade Routes 1400–1600',
    author: 'Marco Foscari',
    language: 'Italian',
    country: 'Croatia',
    city: 'Dubrovnik',
    library: 'Dubrovnik State Archive',
    requestCount: 38,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '4',
    title: 'Medieval Herbal Medicine',
    author: 'Anna Horvat',
    language: 'Croatian',
    country: 'Croatia',
    city: 'Zagreb',
    library: 'National and University Library Zagreb',
    requestCount: 17,
    isDigitized: true,    // already done — should score low
    riskLevel: 'low',
  },
  {
    id: '5',
    title: 'Habsburg Administrative Decrees Vol. III',
    author: 'K. Schmid',
    language: 'German',
    country: 'Austria',
    city: 'Vienna',
    library: 'Austrian National Library',
    requestCount: 45,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '6',
    title: 'Alpine Folklore and Songs',
    author: 'E. Brauer',
    language: 'German',
    country: 'Austria',
    city: 'Innsbruck',
    library: 'University of Innsbruck Library',
    requestCount: 8,
    isDigitized: false,
    riskLevel: 'low',
  },
  {
    id: '7',
    title: 'Ottoman Land Registry — Bosnia 1870',
    author: 'Unknown',
    language: 'Turkish',
    country: 'Bosnia',
    city: 'Sarajevo',
    library: 'Archives of Bosnia-Herzegovina',
    requestCount: 62,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '8',
    title: 'Sarajevo Street Directories 1920–1940',
    author: 'Various',
    language: 'Serbian',
    country: 'Bosnia',
    city: 'Sarajevo',
    library: 'Archives of Bosnia-Herzegovina',
    requestCount: 19,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '9',
    title: 'Prewar Budapest Telephone Books',
    author: 'Budapest City Council',
    language: 'Hungarian',
    country: 'Hungary',
    city: 'Budapest',
    library: 'National Széchényi Library',
    requestCount: 80,
    isDigitized: true,
    riskLevel: 'low',
  },
  {
    id: '10',
    title: 'Transylvanian Church Records',
    author: 'Unknown',
    language: 'Romanian',
    country: 'Romania',
    city: 'Cluj-Napoca',
    library: 'Cluj County Library',
    requestCount: 33,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '11',
    title: 'Polish Resistance Underground Press 1943',
    author: 'Various',
    language: 'Polish',
    country: 'Poland',
    city: 'Warsaw',
    library: 'Warsaw University Library',
    requestCount: 55,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '12',
    title: 'Gdańsk Merchant Guild Ledgers',
    author: 'Guild of St. George',
    language: 'German',
    country: 'Poland',
    city: 'Gdańsk',
    library: 'Gdańsk Library of the Polish Academy',
    requestCount: 27,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '13',
    title: 'Prague Spring Pamphlets',
    author: 'Various',
    language: 'Czech',
    country: 'Czech Republic',
    city: 'Prague',
    library: 'National Library of the Czech Republic',
    requestCount: 41,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '14',
    title: 'Bohemian Mining Regulations 1550',
    author: 'Joachim Gärtner',
    language: 'German',
    country: 'Czech Republic',
    city: 'Prague',
    library: 'National Library of the Czech Republic',
    requestCount: 12,
    isDigitized: true,
    riskLevel: 'low',
  },
  {
    id: '15',
    title: 'Serbian Orthodox Monastery Codex',
    author: 'Unknown',
    language: 'Serbian',
    country: 'Serbia',
    city: 'Novi Sad',
    library: 'Matica srpska Library',
    requestCount: 29,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '16',
    title: 'Istrian Land Survey Maps 1780',
    author: 'Imperial Survey Office',
    language: 'Italian',
    country: 'Croatia',
    city: 'Pula',
    library: 'State Archive Pazin',
    requestCount: 16,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '17',
    title: 'Dalmatian Cookbook Manuscripts',
    author: 'Unknown',
    language: 'Croatian',
    country: 'Croatia',
    city: 'Split',
    library: 'Museum of Croatian Archaeological Monuments',
    requestCount: 7,
    isDigitized: false,
    riskLevel: 'low',
  },
  {
    id: '18',
    title: 'Bulgarian National Revival Journals',
    author: 'Various',
    language: 'Bulgarian',
    country: 'Bulgaria',
    city: 'Sofia',
    library: 'SS Cyril and Methodius National Library',
    requestCount: 34,
    isDigitized: false,
    riskLevel: 'high',
  },
  {
    id: '19',
    title: 'Krakow University Lecture Transcripts 1890',
    author: 'Various',
    language: 'Polish',
    country: 'Poland',
    city: 'Krakow',
    library: 'Jagiellonian Library',
    requestCount: 22,
    isDigitized: false,
    riskLevel: 'medium',
  },
  {
    id: '20',
    title: 'Greek Shipping Manifests — Piraeus 1905',
    author: 'Port Authority of Piraeus',
    language: 'Greek',
    country: 'Greece',
    city: 'Athens',
    library: 'National Library of Greece',
    requestCount: 48,
    isDigitized: false,
    riskLevel: 'high',
  },
];
